name: CI

on:
  push:
  pull_request:

jobs:
  backend-tests:
    name: Backend Clojure tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    services:
      postgres:
        image: postgres:17.5-alpine
        env:
          POSTGRES_DB: rocket-local
          POSTGRES_USER: rocketman
          POSTGRES_PASSWORD: eltonjohn
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U rocketman -d rocket-local"
          --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest  # or pin a version like '1.11.3.1403'

      # Cache Maven repo + git deps to speed up builds
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
          key: ${{ runner.os }}-cljdeps-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-cljdeps-

      - name: Prep dependencies (optional but speeds up)
        run: clojure -P -M:test

      - name: Check formatting
        run: clojure -M:cljfmt check

      - name: Run tests
        run: clojure -M:test
